# Generated by Django 5.2.1 on 2025-05-18 09:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaducidadPorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveIntegerField(unique=True)),
                ('caducidad_tras_apertura', models.PositiveIntegerField(help_text='Meses de caducidad tras apertura')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoReactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('reactivo', models.CharField(max_length=255)),
                ('cas', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cantidad_envases', models.PositiveIntegerField()),
                ('lote_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('lote_eumedica', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medida', models.CharField(blank=True, max_length=50, null=True)),
                ('caducidad', models.DateField(blank=True, null=True)),
                ('log_book', models.CharField(blank=True, max_length=100, null=True)),
                ('pag', models.CharField(blank=True, max_length=50, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('codigo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.codigoreactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=100)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_ud', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('lote_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recibido', models.BooleanField(default=False)),
                ('codigo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.codigoreactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('lote_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('ud', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medida', models.CharField(blank=True, max_length=50, null=True)),
                ('lote_eumedica', models.CharField(blank=True, max_length=100, null=True)),
                ('caducidad', models.DateField(blank=True, null=True)),
                ('log_book', models.CharField(blank=True, max_length=100, null=True)),
                ('pag', models.CharField(blank=True, max_length=50, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('codigo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='reactivos.codigoreactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('lote_eumedica', models.CharField(max_length=50)),
                ('unidades', models.PositiveIntegerField()),
                ('salidas_acumuladas', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.CharField(max_length=100)),
                ('codigo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactivos.codigoreactivo')),
            ],
        ),
    ]
