# Generated by Django 5.2.1 on 2025-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoreactivo',
            name='categoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
