# Generated by Django 5.2.1 on 2025-05-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0002_alter_codigoreactivo_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
