# Generated by Django 5.2.1 on 2025-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_caducidadporcategoria_reactivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='salidas_acum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
